_target_: lsr.datasets.MultipleDatasets
datasets:
  - _target_: lsr.datasets.MultipleNegatives
    collection_path: 'irds:msmarco-passage/train/judged'
    queries_path: 'irds:msmarco-passage/train/judged'
    triplet_ids_path: 'irds:msmarco-passage/train/triples-small'
    train_group_size: 8

  - _target_: lsr.datasets.MultipleNegatives
    collection_path: 'irds:mmarco/fr'
    queries_path: 'irds:msmarco-passage/train/judged'
    triplet_ids_path: 'irds:msmarco-passage/train/triples-small'
    train_group_size: 8
